### ISSUE TITLE
Authentication tracking issue

### ISSUE THREAD

**Issue by peterp** [redwoodjs/example-invoice#31]
## Project structure
- [x] Create `packages` workspace
- [x] Add `@redwoodjs/auth` package

## Web side
- [x] Create a Provider with common Context for auth0 and Netlify Identity
- [x] Allow `auth0` to be passed into Provider
- [x] Map `auth0` methods to our own hooks, and exports
- [x] Create "User tools" in header that allows a user to signup, login, view log in state or log out
- [x] Make the `RedwoodProvider` an optional consumer of the `AuthProvider` so that it can pass the `authToken` along with the requests to the api side.

## API side
- [x] Get an user object from the headers

**Comment by samjulien** [comment]
@peterp as @woloski mentioned [here](https://github.com/redwoodjs/redwood/issues/214), Auth0 is happy to help out here. Let us know what you need!

**Comment by peterp** [comment]
@samjulien thanks so much for this, I'm getting really close and would love some guidance on verify the jwt, this is an ages-old now implementation of doing this on the lambda function:

https://github.com/redwoodjs/example-invoice/blob/master/api/src/lib/auth0.js

I would love some input on my approach, the idea here is to decode and verify the token, so that I can associate this against a user account.

**Comment by samjulien** [comment]
Hey @peterp, sorry for the delay -- somehow the days are simultaneously going by extremely fast and extremely slow. I have no idea how it has been 9 days since you responded to this 😫 .

Looking at that code, that's pretty darn similar to what I just did in a GraphQL example:

https://github.com/samjulien/apollo-auth0-fullstack/blob/master/server/src/utils/verifyToken.js

To my knowledge that's still valid (and we own `jsonwebtoken` and `jwks-rsa` so I know they're maintained). What's behind the scenes of the Redwood API? Is it Express?

**Comment by peterp** [comment]
@samjulien Thanks! I feel the same way regarding time, especially in lockdown.

The dev-server is express, but we're targeting any kind of node based lambda function, I took a slightly different approach over here:

https://github.com/redwoodjs/redwood/blob/64baaedc3208e3b97f80ec0f495339d1181354c0/packages/api/src/getUserFromContext.ts#L26-L41

I'm trying to figure out if there are any downsides to calling `https://<AUTH0_DOMAIN>/userinfo`? I know caching is going to be an issue, but that may also be the case for caching the `jwks.json` file.

**Comment by samjulien** [comment]
I am double-checking this with some of our architects, will let you know what I find!
